/* This file is automatically generated; do not edit. */

#include <ql/experimental/catbonds/catbond.hpp>
#include <ql/experimental/catbonds/catrisk.hpp>
#include <ql/experimental/catbonds/montecarlocatbondengine.hpp>
#include <ql/experimental/catbonds/riskynotional.hpp>
