/* This file is automatically generated; do not edit. */

#include <ql/models/volatility/constantestimator.hpp>
#include <ql/models/volatility/garch.hpp>
#include <ql/models/volatility/garmanklass.hpp>
#include <ql/models/volatility/simplelocalestimator.hpp>
