/* This file is automatically generated; do not edit. */

#include <ql/patterns/curiouslyrecurring.hpp>
#include <ql/patterns/lazyobject.hpp>
#include <ql/patterns/observable.hpp>
#include <ql/patterns/singleton.hpp>
#include <ql/patterns/visitor.hpp>
