/* This file is automatically generated; do not edit. */

#include <ql/currencies/africa.hpp>
#include <ql/currencies/america.hpp>
#include <ql/currencies/asia.hpp>
#include <ql/currencies/crypto.hpp>
#include <ql/currencies/europe.hpp>
#include <ql/currencies/exchangeratemanager.hpp>
#include <ql/currencies/oceania.hpp>
