/* This file is automatically generated; do not edit. */

#include <ql/experimental/averageois/arithmeticaverageois.hpp>
#include <ql/experimental/averageois/arithmeticoisratehelper.hpp>
#include <ql/experimental/averageois/averageoiscouponpricer.hpp>
#include <ql/experimental/averageois/makearithmeticaverageois.hpp>
